//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolarWindDemo.SWIS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfXmlElement", Namespace="http://schemas.datacontract.org/2004/07/System.Xml", ItemName="XmlElement")]
    [System.SerializableAttribute()]
    public class ArrayOfXmlElement : System.Collections.Generic.List<System.Xml.Linq.XElement> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformationServiceFaultContract", Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
    [System.SerializableAttribute()]
    public partial class InformationServiceFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullExceptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UserMessage {
            get {
                return this.UserMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.UserMessageField, value) != true)) {
                    this.UserMessageField = value;
                    this.RaisePropertyChanged("UserMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTypeField, value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FullException {
            get {
                return this.FullExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FullExceptionField, value) != true)) {
                    this.FullExceptionField = value;
                    this.RaisePropertyChanged("FullException");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="dictionary", Namespace="http://schemas.solarwinds.com/2007/08/informationservice/propertybag", ItemName="item")]
    [System.SerializableAttribute()]
    public class dictionary : System.Collections.Generic.List<SolarWindDemo.SWIS.item> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="item", Namespace="http://schemas.solarwinds.com/2007/08/informationservice/propertybag")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolarWindDemo.SWIS.ArrayOfXmlElement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolarWindDemo.SWIS.dictionary))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract))]
    public partial class item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string keyField;
        
        private string typeField;
        
        private object valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                if ((object.ReferenceEquals(this.keyField, value) != true)) {
                    this.keyField = value;
                    this.RaisePropertyChanged("key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", ConfigurationName="SWIS.InformationService")]
    public interface InformationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Invok" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Invok" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Invok" +
            "eInfoServiceFaultContractFault", Name="InformationServiceFaultContract")]
        System.Xml.Linq.XElement Invoke(string entity, string verb, SolarWindDemo.SWIS.ArrayOfXmlElement parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Invok" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Invok" +
            "eResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> InvokeAsync(string entity, string verb, SolarWindDemo.SWIS.ArrayOfXmlElement parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Query" +
            "Xml", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Query" +
            "XmlResponse")]
        System.Xml.Linq.XElement QueryXml(string query, SolarWindDemo.SWIS.dictionary parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Query" +
            "Xml", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Query" +
            "XmlResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> QueryXmlAsync(string query, SolarWindDemo.SWIS.dictionary parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Creat" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Creat" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Creat" +
            "eInfoServiceFaultContractFault", Name="InformationServiceFaultContract")]
        string Create(string entityType, SolarWindDemo.SWIS.dictionary properties);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Creat" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Creat" +
            "eResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(string entityType, SolarWindDemo.SWIS.dictionary properties);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Read", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/ReadR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/ReadI" +
            "nfoServiceFaultContractFault", Name="InformationServiceFaultContract")]
        SolarWindDemo.SWIS.dictionary Read(string uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Read", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/ReadR" +
            "esponse")]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.dictionary> ReadAsync(string uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Updat" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Updat" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Updat" +
            "eInfoServiceFaultContractFault", Name="InformationServiceFaultContract")]
        void Update(string uri, SolarWindDemo.SWIS.dictionary propertiesToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Updat" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Updat" +
            "eResponse")]
        System.Threading.Tasks.Task UpdateAsync(string uri, SolarWindDemo.SWIS.dictionary propertiesToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkU" +
            "pdate", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkU" +
            "pdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkU" +
            "pdateInfoServiceFaultContractFault", Name="InformationServiceFaultContract")]
        void BulkUpdate(string[] uris, SolarWindDemo.SWIS.dictionary propertiesToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkU" +
            "pdate", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkU" +
            "pdateResponse")]
        System.Threading.Tasks.Task BulkUpdateAsync(string[] uris, SolarWindDemo.SWIS.dictionary propertiesToUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Delet" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Delet" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Delet" +
            "eInfoServiceFaultContractFault", Name="InformationServiceFaultContract")]
        void Delete(string uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Delet" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Delet" +
            "eResponse")]
        System.Threading.Tasks.Task DeleteAsync(string uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkD" +
            "elete", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkD" +
            "eleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkD" +
            "eleteInfoServiceFaultContractFault", Name="InformationServiceFaultContract")]
        void BulkDelete(string[] uris);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkD" +
            "elete", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkD" +
            "eleteResponse")]
        System.Threading.Tasks.Task BulkDeleteAsync(string[] uris);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InformationServiceChannel : SolarWindDemo.SWIS.InformationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InformationServiceClient : System.ServiceModel.ClientBase<SolarWindDemo.SWIS.InformationService>, SolarWindDemo.SWIS.InformationService {
        
        public InformationServiceClient() {
        }
        
        public InformationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InformationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InformationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.Linq.XElement Invoke(string entity, string verb, SolarWindDemo.SWIS.ArrayOfXmlElement parameters) {
            return base.Channel.Invoke(entity, verb, parameters);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> InvokeAsync(string entity, string verb, SolarWindDemo.SWIS.ArrayOfXmlElement parameters) {
            return base.Channel.InvokeAsync(entity, verb, parameters);
        }
        
        public System.Xml.Linq.XElement QueryXml(string query, SolarWindDemo.SWIS.dictionary parameters) {
            return base.Channel.QueryXml(query, parameters);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> QueryXmlAsync(string query, SolarWindDemo.SWIS.dictionary parameters) {
            return base.Channel.QueryXmlAsync(query, parameters);
        }
        
        public string Create(string entityType, SolarWindDemo.SWIS.dictionary properties) {
            return base.Channel.Create(entityType, properties);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(string entityType, SolarWindDemo.SWIS.dictionary properties) {
            return base.Channel.CreateAsync(entityType, properties);
        }
        
        public SolarWindDemo.SWIS.dictionary Read(string uri) {
            return base.Channel.Read(uri);
        }
        
        public System.Threading.Tasks.Task<SolarWindDemo.SWIS.dictionary> ReadAsync(string uri) {
            return base.Channel.ReadAsync(uri);
        }
        
        public void Update(string uri, SolarWindDemo.SWIS.dictionary propertiesToUpdate) {
            base.Channel.Update(uri, propertiesToUpdate);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string uri, SolarWindDemo.SWIS.dictionary propertiesToUpdate) {
            return base.Channel.UpdateAsync(uri, propertiesToUpdate);
        }
        
        public void BulkUpdate(string[] uris, SolarWindDemo.SWIS.dictionary propertiesToUpdate) {
            base.Channel.BulkUpdate(uris, propertiesToUpdate);
        }
        
        public System.Threading.Tasks.Task BulkUpdateAsync(string[] uris, SolarWindDemo.SWIS.dictionary propertiesToUpdate) {
            return base.Channel.BulkUpdateAsync(uris, propertiesToUpdate);
        }
        
        public void Delete(string uri) {
            base.Channel.Delete(uri);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string uri) {
            return base.Channel.DeleteAsync(uri);
        }
        
        public void BulkDelete(string[] uris) {
            base.Channel.BulkDelete(uris);
        }
        
        public System.Threading.Tasks.Task BulkDeleteAsync(string[] uris) {
            return base.Channel.BulkDeleteAsync(uris);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWIS.IRestInformationService")]
    public interface IRestInformationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/Query", ReplyAction="http://tempuri.org/IRestInformationService/QueryResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SolarWindDemo.SWIS.ArrayOfXmlElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SolarWindDemo.SWIS.dictionary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract))]
        object Query([System.ServiceModel.MessageParameterAttribute(Name="query")] string query1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/Query", ReplyAction="http://tempuri.org/IRestInformationService/QueryResponse")]
        System.Threading.Tasks.Task<object> QueryAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/QueryWithParameters", ReplyAction="http://tempuri.org/IRestInformationService/QueryWithParametersResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SolarWindDemo.SWIS.ArrayOfXmlElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SolarWindDemo.SWIS.dictionary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract))]
        object QueryWithParameters(System.Collections.Generic.Dictionary<string, object> queryAndParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/QueryWithParameters", ReplyAction="http://tempuri.org/IRestInformationService/QueryWithParametersResponse")]
        System.Threading.Tasks.Task<object> QueryWithParametersAsync(System.Collections.Generic.Dictionary<string, object> queryAndParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/Invoke", ReplyAction="http://tempuri.org/IRestInformationService/InvokeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SolarWindDemo.SWIS.ArrayOfXmlElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SolarWindDemo.SWIS.dictionary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        object Invoke(string entityType, string verbName, object parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/Invoke", ReplyAction="http://tempuri.org/IRestInformationService/InvokeResponse")]
        System.Threading.Tasks.Task<object> InvokeAsync(string entityType, string verbName, object parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/Create", ReplyAction="http://tempuri.org/IRestInformationService/CreateResponse")]
        string Create(string entityType, System.Collections.Generic.Dictionary<string, object> properties);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/Create", ReplyAction="http://tempuri.org/IRestInformationService/CreateResponse")]
        System.Threading.Tasks.Task<string> CreateAsync(string entityType, System.Collections.Generic.Dictionary<string, object> properties);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/Read", ReplyAction="http://tempuri.org/IRestInformationService/ReadResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SolarWindDemo.SWIS.ArrayOfXmlElement))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(string[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(byte[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SolarWindDemo.SWIS.dictionary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract))]
        object Read(string uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/Read", ReplyAction="http://tempuri.org/IRestInformationService/ReadResponse")]
        System.Threading.Tasks.Task<object> ReadAsync(string uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/Update", ReplyAction="http://tempuri.org/IRestInformationService/UpdateResponse")]
        void Update(string uri, System.Collections.Generic.Dictionary<string, object> properties);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/Update", ReplyAction="http://tempuri.org/IRestInformationService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(string uri, System.Collections.Generic.Dictionary<string, object> properties);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/BulkUpdate", ReplyAction="http://tempuri.org/IRestInformationService/BulkUpdateResponse")]
        void BulkUpdate(string[] uris, System.Collections.Generic.Dictionary<string, object> properties);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/BulkUpdate", ReplyAction="http://tempuri.org/IRestInformationService/BulkUpdateResponse")]
        System.Threading.Tasks.Task BulkUpdateAsync(string[] uris, System.Collections.Generic.Dictionary<string, object> properties);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/Delete", ReplyAction="http://tempuri.org/IRestInformationService/DeleteResponse")]
        void Delete(string uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/Delete", ReplyAction="http://tempuri.org/IRestInformationService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(string uri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/BulkDelete", ReplyAction="http://tempuri.org/IRestInformationService/BulkDeleteResponse")]
        void BulkDelete(string[] uris);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestInformationService/BulkDelete", ReplyAction="http://tempuri.org/IRestInformationService/BulkDeleteResponse")]
        System.Threading.Tasks.Task BulkDeleteAsync(string[] uris);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestInformationServiceChannel : SolarWindDemo.SWIS.IRestInformationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestInformationServiceClient : System.ServiceModel.ClientBase<SolarWindDemo.SWIS.IRestInformationService>, SolarWindDemo.SWIS.IRestInformationService {
        
        public RestInformationServiceClient() {
        }
        
        public RestInformationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestInformationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestInformationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestInformationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object Query(string query1) {
            return base.Channel.Query(query1);
        }
        
        public System.Threading.Tasks.Task<object> QueryAsync(string query) {
            return base.Channel.QueryAsync(query);
        }
        
        public object QueryWithParameters(System.Collections.Generic.Dictionary<string, object> queryAndParameters) {
            return base.Channel.QueryWithParameters(queryAndParameters);
        }
        
        public System.Threading.Tasks.Task<object> QueryWithParametersAsync(System.Collections.Generic.Dictionary<string, object> queryAndParameters) {
            return base.Channel.QueryWithParametersAsync(queryAndParameters);
        }
        
        public object Invoke(string entityType, string verbName, object parameters) {
            return base.Channel.Invoke(entityType, verbName, parameters);
        }
        
        public System.Threading.Tasks.Task<object> InvokeAsync(string entityType, string verbName, object parameters) {
            return base.Channel.InvokeAsync(entityType, verbName, parameters);
        }
        
        public string Create(string entityType, System.Collections.Generic.Dictionary<string, object> properties) {
            return base.Channel.Create(entityType, properties);
        }
        
        public System.Threading.Tasks.Task<string> CreateAsync(string entityType, System.Collections.Generic.Dictionary<string, object> properties) {
            return base.Channel.CreateAsync(entityType, properties);
        }
        
        public object Read(string uri) {
            return base.Channel.Read(uri);
        }
        
        public System.Threading.Tasks.Task<object> ReadAsync(string uri) {
            return base.Channel.ReadAsync(uri);
        }
        
        public void Update(string uri, System.Collections.Generic.Dictionary<string, object> properties) {
            base.Channel.Update(uri, properties);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(string uri, System.Collections.Generic.Dictionary<string, object> properties) {
            return base.Channel.UpdateAsync(uri, properties);
        }
        
        public void BulkUpdate(string[] uris, System.Collections.Generic.Dictionary<string, object> properties) {
            base.Channel.BulkUpdate(uris, properties);
        }
        
        public System.Threading.Tasks.Task BulkUpdateAsync(string[] uris, System.Collections.Generic.Dictionary<string, object> properties) {
            return base.Channel.BulkUpdateAsync(uris, properties);
        }
        
        public void Delete(string uri) {
            base.Channel.Delete(uri);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(string uri) {
            return base.Channel.DeleteAsync(uri);
        }
        
        public void BulkDelete(string[] uris) {
            base.Channel.BulkDelete(uris);
        }
        
        public System.Threading.Tasks.Task BulkDeleteAsync(string[] uris) {
            return base.Channel.BulkDeleteAsync(uris);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SWIS.IStreamInformationService")]
    public interface IStreamInformationService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.solarwinds.com/2007/08/informationservice) of message InvokeRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Invok" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Invok" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Invok" +
            "eInfoServiceFaultContractFault", Name="InformationServiceFaultContract", Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
        SolarWindDemo.SWIS.InvokeResponse Invoke(SolarWindDemo.SWIS.InvokeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Invok" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Invok" +
            "eResponse")]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.InvokeResponse> InvokeAsync(SolarWindDemo.SWIS.InvokeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.solarwinds.com/2007/08/informationservice) of message QueryXmlRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Query" +
            "Xml", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Query" +
            "XmlResponse")]
        SolarWindDemo.SWIS.QueryXmlResponse QueryXml(SolarWindDemo.SWIS.QueryXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Query" +
            "Xml", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Query" +
            "XmlResponse")]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.QueryXmlResponse> QueryXmlAsync(SolarWindDemo.SWIS.QueryXmlRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.solarwinds.com/2007/08/informationservice) of message CreateRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Creat" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Creat" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Creat" +
            "eInfoServiceFaultContractFault", Name="InformationServiceFaultContract", Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
        SolarWindDemo.SWIS.CreateResponse Create(SolarWindDemo.SWIS.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Creat" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Creat" +
            "eResponse")]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.CreateResponse> CreateAsync(SolarWindDemo.SWIS.CreateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.solarwinds.com/2007/08/informationservice) of message ReadRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Read", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/ReadR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/ReadI" +
            "nfoServiceFaultContractFault", Name="InformationServiceFaultContract", Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
        SolarWindDemo.SWIS.ReadResponse Read(SolarWindDemo.SWIS.ReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Read", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/ReadR" +
            "esponse")]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.ReadResponse> ReadAsync(SolarWindDemo.SWIS.ReadRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.solarwinds.com/2007/08/informationservice) of message UpdateRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Updat" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Updat" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Updat" +
            "eInfoServiceFaultContractFault", Name="InformationServiceFaultContract", Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
        SolarWindDemo.SWIS.UpdateResponse Update(SolarWindDemo.SWIS.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Updat" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Updat" +
            "eResponse")]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.UpdateResponse> UpdateAsync(SolarWindDemo.SWIS.UpdateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.solarwinds.com/2007/08/informationservice) of message BulkUpdateRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkU" +
            "pdate", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkU" +
            "pdateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkU" +
            "pdateInfoServiceFaultContractFault", Name="InformationServiceFaultContract", Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
        SolarWindDemo.SWIS.BulkUpdateResponse BulkUpdate(SolarWindDemo.SWIS.BulkUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkU" +
            "pdate", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkU" +
            "pdateResponse")]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.BulkUpdateResponse> BulkUpdateAsync(SolarWindDemo.SWIS.BulkUpdateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.solarwinds.com/2007/08/informationservice) of message DeleteRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Delet" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Delet" +
            "eResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Delet" +
            "eInfoServiceFaultContractFault", Name="InformationServiceFaultContract", Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
        SolarWindDemo.SWIS.DeleteResponse Delete(SolarWindDemo.SWIS.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Delet" +
            "e", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Delet" +
            "eResponse")]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.DeleteResponse> DeleteAsync(SolarWindDemo.SWIS.DeleteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.solarwinds.com/2007/08/informationservice) of message BulkDeleteRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkD" +
            "elete", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkD" +
            "eleteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkD" +
            "eleteInfoServiceFaultContractFault", Name="InformationServiceFaultContract", Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
        SolarWindDemo.SWIS.BulkDeleteResponse BulkDelete(SolarWindDemo.SWIS.BulkDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkD" +
            "elete", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/BulkD" +
            "eleteResponse")]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.BulkDeleteResponse> BulkDeleteAsync(SolarWindDemo.SWIS.BulkDeleteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://schemas.solarwinds.com/2007/08/informationservice) of message VerbInvokeArguments does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Strea" +
            "med/Invoke", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Strea" +
            "med/InvokeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SolarWindDemo.SWIS.InformationServiceFaultContract), Action="http://tempuri.org/IStreamInformationService/StreamedInvokeInfoServiceFaultContra" +
            "ctFault", Name="InformationServiceFaultContract", Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
        SolarWindDemo.SWIS.VerbInvokeResponse StreamedInvoke(SolarWindDemo.SWIS.VerbInvokeArguments request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Strea" +
            "med/Invoke", ReplyAction="http://schemas.solarwinds.com/2007/08/informationservice/InformationService/Strea" +
            "med/InvokeResponse")]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.VerbInvokeResponse> StreamedInvokeAsync(SolarWindDemo.SWIS.VerbInvokeArguments request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Invoke", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class InvokeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public string entity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=1)]
        public string verb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=2)]
        public SolarWindDemo.SWIS.ArrayOfXmlElement parameters;
        
        public InvokeRequest() {
        }
        
        public InvokeRequest(string entity, string verb, SolarWindDemo.SWIS.ArrayOfXmlElement parameters) {
            this.entity = entity;
            this.verb = verb;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InvokeResponse", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class InvokeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public System.Xml.Linq.XElement InvokeResult;
        
        public InvokeResponse() {
        }
        
        public InvokeResponse(System.Xml.Linq.XElement InvokeResult) {
            this.InvokeResult = InvokeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryXml", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class QueryXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public string query;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=1)]
        public SolarWindDemo.SWIS.dictionary parameters;
        
        public QueryXmlRequest() {
        }
        
        public QueryXmlRequest(string query, SolarWindDemo.SWIS.dictionary parameters) {
            this.query = query;
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryXmlResponse", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class QueryXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public System.Xml.Linq.XElement QueryXmlResult;
        
        public QueryXmlResponse() {
        }
        
        public QueryXmlResponse(System.Xml.Linq.XElement QueryXmlResult) {
            this.QueryXmlResult = QueryXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Create", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class CreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public string entityType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=1)]
        public SolarWindDemo.SWIS.dictionary properties;
        
        public CreateRequest() {
        }
        
        public CreateRequest(string entityType, SolarWindDemo.SWIS.dictionary properties) {
            this.entityType = entityType;
            this.properties = properties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateResponse", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class CreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public string CreateResult;
        
        public CreateResponse() {
        }
        
        public CreateResponse(string CreateResult) {
            this.CreateResult = CreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class ReadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public string uri;
        
        public ReadRequest() {
        }
        
        public ReadRequest(string uri) {
            this.uri = uri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadResponse", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class ReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public SolarWindDemo.SWIS.dictionary ReadResult;
        
        public ReadResponse() {
        }
        
        public ReadResponse(SolarWindDemo.SWIS.dictionary ReadResult) {
            this.ReadResult = ReadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Update", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public string uri;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=1)]
        public SolarWindDemo.SWIS.dictionary propertiesToUpdate;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(string uri, SolarWindDemo.SWIS.dictionary propertiesToUpdate) {
            this.uri = uri;
            this.propertiesToUpdate = propertiesToUpdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateResponse", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class UpdateResponse {
        
        public UpdateResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BulkUpdate", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class BulkUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public string[] uris;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=1)]
        public SolarWindDemo.SWIS.dictionary propertiesToUpdate;
        
        public BulkUpdateRequest() {
        }
        
        public BulkUpdateRequest(string[] uris, SolarWindDemo.SWIS.dictionary propertiesToUpdate) {
            this.uris = uris;
            this.propertiesToUpdate = propertiesToUpdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BulkUpdateResponse", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class BulkUpdateResponse {
        
        public BulkUpdateResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Delete", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public string uri;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(string uri) {
            this.uri = uri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteResponse", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class DeleteResponse {
        
        public DeleteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BulkDelete", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class BulkDeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public string[] uris;
        
        public BulkDeleteRequest() {
        }
        
        public BulkDeleteRequest(string[] uris) {
            this.uris = uris;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BulkDeleteResponse", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class BulkDeleteResponse {
        
        public BulkDeleteResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerbInvokeArguments", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class VerbInvokeArguments {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
        public string Entity;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
        public SolarWindDemo.SWIS.ArrayOfXmlElement Parameters;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
        public string Verb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public System.IO.Stream Content;
        
        public VerbInvokeArguments() {
        }
        
        public VerbInvokeArguments(string Entity, SolarWindDemo.SWIS.ArrayOfXmlElement Parameters, string Verb, System.IO.Stream Content) {
            this.Entity = Entity;
            this.Parameters = Parameters;
            this.Verb = Verb;
            this.Content = Content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerbInvokeResponse", WrapperNamespace="http://schemas.solarwinds.com/2007/08/informationservice", IsWrapped=true)]
    public partial class VerbInvokeResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice")]
        public System.Xml.Linq.XElement Response;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.solarwinds.com/2007/08/informationservice", Order=0)]
        public System.IO.Stream Content;
        
        public VerbInvokeResponse() {
        }
        
        public VerbInvokeResponse(System.Xml.Linq.XElement Response, System.IO.Stream Content) {
            this.Response = Response;
            this.Content = Content;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStreamInformationServiceChannel : SolarWindDemo.SWIS.IStreamInformationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StreamInformationServiceClient : System.ServiceModel.ClientBase<SolarWindDemo.SWIS.IStreamInformationService>, SolarWindDemo.SWIS.IStreamInformationService {
        
        public StreamInformationServiceClient() {
        }
        
        public StreamInformationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StreamInformationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamInformationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StreamInformationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SolarWindDemo.SWIS.InvokeResponse SolarWindDemo.SWIS.IStreamInformationService.Invoke(SolarWindDemo.SWIS.InvokeRequest request) {
            return base.Channel.Invoke(request);
        }
        
        public System.Xml.Linq.XElement Invoke(string entity, string verb, SolarWindDemo.SWIS.ArrayOfXmlElement parameters) {
            SolarWindDemo.SWIS.InvokeRequest inValue = new SolarWindDemo.SWIS.InvokeRequest();
            inValue.entity = entity;
            inValue.verb = verb;
            inValue.parameters = parameters;
            SolarWindDemo.SWIS.InvokeResponse retVal = ((SolarWindDemo.SWIS.IStreamInformationService)(this)).Invoke(inValue);
            return retVal.InvokeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.InvokeResponse> SolarWindDemo.SWIS.IStreamInformationService.InvokeAsync(SolarWindDemo.SWIS.InvokeRequest request) {
            return base.Channel.InvokeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SolarWindDemo.SWIS.InvokeResponse> InvokeAsync(string entity, string verb, SolarWindDemo.SWIS.ArrayOfXmlElement parameters) {
            SolarWindDemo.SWIS.InvokeRequest inValue = new SolarWindDemo.SWIS.InvokeRequest();
            inValue.entity = entity;
            inValue.verb = verb;
            inValue.parameters = parameters;
            return ((SolarWindDemo.SWIS.IStreamInformationService)(this)).InvokeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SolarWindDemo.SWIS.QueryXmlResponse SolarWindDemo.SWIS.IStreamInformationService.QueryXml(SolarWindDemo.SWIS.QueryXmlRequest request) {
            return base.Channel.QueryXml(request);
        }
        
        public System.Xml.Linq.XElement QueryXml(string query, SolarWindDemo.SWIS.dictionary parameters) {
            SolarWindDemo.SWIS.QueryXmlRequest inValue = new SolarWindDemo.SWIS.QueryXmlRequest();
            inValue.query = query;
            inValue.parameters = parameters;
            SolarWindDemo.SWIS.QueryXmlResponse retVal = ((SolarWindDemo.SWIS.IStreamInformationService)(this)).QueryXml(inValue);
            return retVal.QueryXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.QueryXmlResponse> SolarWindDemo.SWIS.IStreamInformationService.QueryXmlAsync(SolarWindDemo.SWIS.QueryXmlRequest request) {
            return base.Channel.QueryXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<SolarWindDemo.SWIS.QueryXmlResponse> QueryXmlAsync(string query, SolarWindDemo.SWIS.dictionary parameters) {
            SolarWindDemo.SWIS.QueryXmlRequest inValue = new SolarWindDemo.SWIS.QueryXmlRequest();
            inValue.query = query;
            inValue.parameters = parameters;
            return ((SolarWindDemo.SWIS.IStreamInformationService)(this)).QueryXmlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SolarWindDemo.SWIS.CreateResponse SolarWindDemo.SWIS.IStreamInformationService.Create(SolarWindDemo.SWIS.CreateRequest request) {
            return base.Channel.Create(request);
        }
        
        public string Create(string entityType, SolarWindDemo.SWIS.dictionary properties) {
            SolarWindDemo.SWIS.CreateRequest inValue = new SolarWindDemo.SWIS.CreateRequest();
            inValue.entityType = entityType;
            inValue.properties = properties;
            SolarWindDemo.SWIS.CreateResponse retVal = ((SolarWindDemo.SWIS.IStreamInformationService)(this)).Create(inValue);
            return retVal.CreateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.CreateResponse> SolarWindDemo.SWIS.IStreamInformationService.CreateAsync(SolarWindDemo.SWIS.CreateRequest request) {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SolarWindDemo.SWIS.CreateResponse> CreateAsync(string entityType, SolarWindDemo.SWIS.dictionary properties) {
            SolarWindDemo.SWIS.CreateRequest inValue = new SolarWindDemo.SWIS.CreateRequest();
            inValue.entityType = entityType;
            inValue.properties = properties;
            return ((SolarWindDemo.SWIS.IStreamInformationService)(this)).CreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SolarWindDemo.SWIS.ReadResponse SolarWindDemo.SWIS.IStreamInformationService.Read(SolarWindDemo.SWIS.ReadRequest request) {
            return base.Channel.Read(request);
        }
        
        public SolarWindDemo.SWIS.dictionary Read(string uri) {
            SolarWindDemo.SWIS.ReadRequest inValue = new SolarWindDemo.SWIS.ReadRequest();
            inValue.uri = uri;
            SolarWindDemo.SWIS.ReadResponse retVal = ((SolarWindDemo.SWIS.IStreamInformationService)(this)).Read(inValue);
            return retVal.ReadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.ReadResponse> SolarWindDemo.SWIS.IStreamInformationService.ReadAsync(SolarWindDemo.SWIS.ReadRequest request) {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<SolarWindDemo.SWIS.ReadResponse> ReadAsync(string uri) {
            SolarWindDemo.SWIS.ReadRequest inValue = new SolarWindDemo.SWIS.ReadRequest();
            inValue.uri = uri;
            return ((SolarWindDemo.SWIS.IStreamInformationService)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SolarWindDemo.SWIS.UpdateResponse SolarWindDemo.SWIS.IStreamInformationService.Update(SolarWindDemo.SWIS.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public void Update(string uri, SolarWindDemo.SWIS.dictionary propertiesToUpdate) {
            SolarWindDemo.SWIS.UpdateRequest inValue = new SolarWindDemo.SWIS.UpdateRequest();
            inValue.uri = uri;
            inValue.propertiesToUpdate = propertiesToUpdate;
            SolarWindDemo.SWIS.UpdateResponse retVal = ((SolarWindDemo.SWIS.IStreamInformationService)(this)).Update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.UpdateResponse> SolarWindDemo.SWIS.IStreamInformationService.UpdateAsync(SolarWindDemo.SWIS.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SolarWindDemo.SWIS.UpdateResponse> UpdateAsync(string uri, SolarWindDemo.SWIS.dictionary propertiesToUpdate) {
            SolarWindDemo.SWIS.UpdateRequest inValue = new SolarWindDemo.SWIS.UpdateRequest();
            inValue.uri = uri;
            inValue.propertiesToUpdate = propertiesToUpdate;
            return ((SolarWindDemo.SWIS.IStreamInformationService)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SolarWindDemo.SWIS.BulkUpdateResponse SolarWindDemo.SWIS.IStreamInformationService.BulkUpdate(SolarWindDemo.SWIS.BulkUpdateRequest request) {
            return base.Channel.BulkUpdate(request);
        }
        
        public void BulkUpdate(string[] uris, SolarWindDemo.SWIS.dictionary propertiesToUpdate) {
            SolarWindDemo.SWIS.BulkUpdateRequest inValue = new SolarWindDemo.SWIS.BulkUpdateRequest();
            inValue.uris = uris;
            inValue.propertiesToUpdate = propertiesToUpdate;
            SolarWindDemo.SWIS.BulkUpdateResponse retVal = ((SolarWindDemo.SWIS.IStreamInformationService)(this)).BulkUpdate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.BulkUpdateResponse> SolarWindDemo.SWIS.IStreamInformationService.BulkUpdateAsync(SolarWindDemo.SWIS.BulkUpdateRequest request) {
            return base.Channel.BulkUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<SolarWindDemo.SWIS.BulkUpdateResponse> BulkUpdateAsync(string[] uris, SolarWindDemo.SWIS.dictionary propertiesToUpdate) {
            SolarWindDemo.SWIS.BulkUpdateRequest inValue = new SolarWindDemo.SWIS.BulkUpdateRequest();
            inValue.uris = uris;
            inValue.propertiesToUpdate = propertiesToUpdate;
            return ((SolarWindDemo.SWIS.IStreamInformationService)(this)).BulkUpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SolarWindDemo.SWIS.DeleteResponse SolarWindDemo.SWIS.IStreamInformationService.Delete(SolarWindDemo.SWIS.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public void Delete(string uri) {
            SolarWindDemo.SWIS.DeleteRequest inValue = new SolarWindDemo.SWIS.DeleteRequest();
            inValue.uri = uri;
            SolarWindDemo.SWIS.DeleteResponse retVal = ((SolarWindDemo.SWIS.IStreamInformationService)(this)).Delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.DeleteResponse> SolarWindDemo.SWIS.IStreamInformationService.DeleteAsync(SolarWindDemo.SWIS.DeleteRequest request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SolarWindDemo.SWIS.DeleteResponse> DeleteAsync(string uri) {
            SolarWindDemo.SWIS.DeleteRequest inValue = new SolarWindDemo.SWIS.DeleteRequest();
            inValue.uri = uri;
            return ((SolarWindDemo.SWIS.IStreamInformationService)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SolarWindDemo.SWIS.BulkDeleteResponse SolarWindDemo.SWIS.IStreamInformationService.BulkDelete(SolarWindDemo.SWIS.BulkDeleteRequest request) {
            return base.Channel.BulkDelete(request);
        }
        
        public void BulkDelete(string[] uris) {
            SolarWindDemo.SWIS.BulkDeleteRequest inValue = new SolarWindDemo.SWIS.BulkDeleteRequest();
            inValue.uris = uris;
            SolarWindDemo.SWIS.BulkDeleteResponse retVal = ((SolarWindDemo.SWIS.IStreamInformationService)(this)).BulkDelete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.BulkDeleteResponse> SolarWindDemo.SWIS.IStreamInformationService.BulkDeleteAsync(SolarWindDemo.SWIS.BulkDeleteRequest request) {
            return base.Channel.BulkDeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SolarWindDemo.SWIS.BulkDeleteResponse> BulkDeleteAsync(string[] uris) {
            SolarWindDemo.SWIS.BulkDeleteRequest inValue = new SolarWindDemo.SWIS.BulkDeleteRequest();
            inValue.uris = uris;
            return ((SolarWindDemo.SWIS.IStreamInformationService)(this)).BulkDeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SolarWindDemo.SWIS.VerbInvokeResponse SolarWindDemo.SWIS.IStreamInformationService.StreamedInvoke(SolarWindDemo.SWIS.VerbInvokeArguments request) {
            return base.Channel.StreamedInvoke(request);
        }
        
        public System.Xml.Linq.XElement StreamedInvoke(string Entity, SolarWindDemo.SWIS.ArrayOfXmlElement Parameters, string Verb, ref System.IO.Stream Content) {
            SolarWindDemo.SWIS.VerbInvokeArguments inValue = new SolarWindDemo.SWIS.VerbInvokeArguments();
            inValue.Entity = Entity;
            inValue.Parameters = Parameters;
            inValue.Verb = Verb;
            inValue.Content = Content;
            SolarWindDemo.SWIS.VerbInvokeResponse retVal = ((SolarWindDemo.SWIS.IStreamInformationService)(this)).StreamedInvoke(inValue);
            Content = retVal.Content;
            return retVal.Response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SolarWindDemo.SWIS.VerbInvokeResponse> SolarWindDemo.SWIS.IStreamInformationService.StreamedInvokeAsync(SolarWindDemo.SWIS.VerbInvokeArguments request) {
            return base.Channel.StreamedInvokeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SolarWindDemo.SWIS.VerbInvokeResponse> StreamedInvokeAsync(string Entity, SolarWindDemo.SWIS.ArrayOfXmlElement Parameters, string Verb, System.IO.Stream Content) {
            SolarWindDemo.SWIS.VerbInvokeArguments inValue = new SolarWindDemo.SWIS.VerbInvokeArguments();
            inValue.Entity = Entity;
            inValue.Parameters = Parameters;
            inValue.Verb = Verb;
            inValue.Content = Content;
            return ((SolarWindDemo.SWIS.IStreamInformationService)(this)).StreamedInvokeAsync(inValue);
        }
    }
}
